"""empty message

Revision ID: f947550576b3
Revises: 9d4541bda5b3
Create Date: 2022-08-08 16:30:08.560782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f947550576b3'
down_revision = '9d4541bda5b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
